# Generated by Django 5.0.6 on 2024-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('-', '-'), ('male', 'чоловік'), ('female', 'жінка')], default='-', max_length=6),
        ),
    ]
